### ISSUE TITLE
ugly_print main function?

### ISSUE THREAD

**Issue by EliottFlechtner** [lance-leau/SudokuSolver#1]
I kind of don't understand the use of your **uglyPrint** function. Why do you need a main function to directly call an auxiliary. I don't know Lancelot, you've been seeming sus lately (la ref si tu l'as pas : https://www.youtube.com/watch?v=zVE1LRxEJs4)

**Comment by lance-leau** [comment]
Thank you for taking the time to review the my code. The point of the uglyPrint function is to print the grid conforming to the format given by the documentation (see doc page 10: http://www.debug-pro.com/epita/prog/s3s/project/ocr_sudoku_solver_fr.pdf). While the use of this format is not **required**, it is however recommended. Moreover, uglyPrint requires an auxiliary function witch uses a parameter 'i' that represents the index of the cell being printed.

**Comment by EliottFlechtner** [comment]
You leaked the subject, watch out boy
